### ISSUE TITLE
Giving more informations about other clients when they send a message

### ISSUE THREAD

**Issue by Annwenn** [bitwalker/exirc#37]
I am writing an "offline notes" module for an IRC bot where I need to access some informations about the sender of a message (to ExIrc), including its username and host.
Do you think it'd be possible to send a struct to the `handler` module, from which one could do pattern matching on `from.nickname`, `from.username`, `from.host`, instead of just sending the nick? Or maybe it's already available, then I'd be more than happy to know I can access this data. =)

**Comment by Annwenn** [comment]
I'm completely aware that this needs to redesign parts of the API. @bitwalker if you have a work-around in mind, I'd like to hear it.

**Comment by bitwalker** [comment]
The data you need is already in the IrcMessage struct, but in the Client module, receiving a message is proxied to event handlers as `{:received, message, from, to}`. If you forked exirc and added the IrcMessage struct which is present when `send_event` is called as an additional element, you'd have what you need.

If you are interested in developing a PR to be merged though, what I'd really like to do is change the existing tuple-based events to a map which always has at least `:type` and `:raw` keys, where `:type` is what is currently the first element of all the event tuples (an atom such as :connected, etc.), and `:raw` is the originating `IrcMessage` struct, or nil if one is not relevant. Since many of the events have different structures, using a struct doesn't really make sense, but moving to maps will make API changes like this less painful in the future (if you are matching on a event map, you don't have to care about new keys which are added, while you do with the existing tuple structure).

**Comment by Annwenn** [comment]
> If you forked exirc and added the IrcMessage struct which is present when send_event is called as an additional element, you'd have what you need.

I think I'm going to go with this, for the moment.

> If you are interested in developing a PR…

I am, but lack of free time isn't going to to help. However, I'm pretty sure that if you, as the maintainer,
wrote that somewhere as a milestone for a next version, people (with more skills) would surely help. :)
Thanks.

**Comment by bitwalker** [comment]
I can relate :). I'll see what I can do about getting that refactor on the TODO list.
