### ISSUE TITLE
Do messages have timestamps? 

### ISSUE THREAD

**Issue by mrlamroger** [bitwalker/exirc#39]
Hi,

Thanks for creating this project! 

I was wondering if IRC servers provide a timestamp with each message. I'm trying to use timestamps as a way to prevent duplicate counts.

**Comment by bitwalker** [comment]
I haven't actually looked when testing, but I suppose it's possible. I'm pretty sure they don't though, because it's unclear to me what would be responsible for timestamping the messages - it would have to be the client in order to prevent duplicates, but there would be no guarantee with regards to order of messages, so you couldn't use the timestamp for absolute ordering. On top of that there would also be no guarantee that timestamps wouldn't collide, so you'd have to de-dupe based on user and timestamp, but I'm not sure how you'd do that since you can't just track the last message received from a given user, because the duplicates might have come out of order.

That said, an easy way to test with a given server would be to drop a IO.inspect on line 674 of `client.ex`, and inspect the IrcMessage struct, as it will contain all of the data received from the server. You could use that to retrieve the timestamp if it's there. If it is something relatively standard, we can add something to exirc to parse that out and include it in event callbacks.
