### ISSUE TITLE
Support for catching the /QUIT command

### ISSUE THREAD

**Issue by w1gz** [bitwalker/exirc#40]
Hi !
I'm playing with my IRC bot ([methal9k](https://github.com/w1gz/methal9k)) and noticed a weird behaviour
with the [channel_has_user?](https://github.com/bitwalker/exirc/blob/master/lib/exirc/client.ex#L218) function inside the client.ex. It was returning true even though the person was disconnect for a while.

With a few grep & tests, I finally found the problem: You catch the /PART command but not the /QUIT (you can see it over [there](https://github.com/bitwalker/exirc/blob/master/lib/exirc/client.ex#L629)). I tried a few hacks but that didn't work out... so here I am ;).

Do you acknowledge this «issue» ? Do you want a PR ? I just took a quick overview of the code and I'm not sure where to start as the ExIRC library is not that small! 

So any help/pointers will be greatly appreciated :)

Cheers

**Comment by jeffweiss** [comment]
Ah, so it sounds like there are two distinct issues at play here:
1) `/QUIT` is not handled at all by `ExIrc.Client`, so quits show up as `:unrecognized` messages with a payload like this:
```elixir
{:unrecognized, "QUIT", 
  %IrcMessage{
    args: ["Ping timeout: 248 seconds"], 
    cmd: "QUIT", 
    ctcp: false, 
    host: "2601:1c2:4c00:e27a:7cd1:855d:4f5a:a300", 
    nick: "jeffweiss", 
    server: [], 
    user: "~jeffweiss"}
}
```
2) Because the `ExIrc.Client` doesn't do anything with `/QUIT`, `ExIrc.Channels.user_part/3` is never called when a `QUIT` is sent, resulting in a wrong answer to `ExIrc.Channels.channel_has_user?/3`.

**Comment by bitwalker** [comment]
Ah interesting, that should be an easy fix. Added to my TODO, but if any of you are in the source already, go for it and I'll be happy to merge.

**Comment by w1gz** [comment]
I wanted to answer and look at the code but it's already done! Thank you very much @jeffweiss, you're fast on your PR :)
