### ISSUE TITLE
SenderInfo struct is backwards-incompatible

### ISSUE THREAD

**Issue by jeffweiss** [bitwalker/exirc#47]
As I was beginning work on #40, I just encountered, the hard way, that `ExIrc.SenderInfo` as added to handler payloads in #41, #42. #43 is backwards-incompatible.
Previous handlers expected a binary for the `from` element of the tuple, but are now receiving the `ExIrc.SenderInfo` struct.

Unless people are explicit about which version of ExIrc they're using, their handlers will need to migrate from
```elixir
def handle_info({:received, msg, user, channel}, state) do
  ...
end
```
to
```elixir
def handle_info({:received, msg, user, channel}, state) when is_binary(user) do
  ...
end
def handle_info({:received, msg, %{nick: user}, channel}, state) do
  ...
end
```
I don't at all think the change should be reverted. I'm mostly documenting here before a new release is packaged so we can formulate a plan.

**Comment by bitwalker** [comment]
@jeffweiss Yeah my plan for this was to do a major version bump for the next release since this is a breaking change, anyone who has exirc via `{:exirc, "~> 0.10"}` or whatever would be protected from accidentally upgrading into a broken state. Documenting the change in a CHANGELOG (like I'm doing on other projects now) would be the next step, and adding a Migrating section to the README to ease the transition. After that we have to assume that anyone explicitly upgrading to a 1.x release would be cognizant enough to check for things which might break along the way.

Thoughts?

**Comment by jeffweiss** [comment]
@bitwalker A+ plan. I simply didn't know how close you felt to a 1.0 release. Plus, I _think_ semver allows for breaking changes in pre-1.0 .

**Comment by bitwalker** [comment]
Cool :) - and yeah semver does allow for that, but it also mandates that if something is being used in production (which from my perspective is "are people writing software which depends on it" in addition to "is this the API I'm happy with for 1.0") that it shouldn't be versioned pre-1.0. So between that and the fact that exirc has been pretty stable as far as feature set goes, and there are enough people using it and enough software depending on it, I think it's probably time :)

**Comment by bitwalker** [comment]
As far as timeframe though, I just merged the last of the pending PRs, so I'll probably push it this weekend unless something comes up
