### ISSUE TITLE
Use within supervision tree

### ISSUE THREAD

**Issue by michalmuskala** [bitwalker/exirc#49]
I'm having a hard time figuring out how to properly use ExIRC within a process in a supervision tree.

The normal flow, as I understand it, is to start the client from within one of the processes in my supervision tree. But here's the problem:

  * if I simply start it and get a pid back, when the exirc client crashes, it will be restarted by the exirc supervisor, but the pid I got is no longer valid - errors will follow.
  * if I monitor the client prcess then when it dies, I could start a new one. The problem is the exirc supervisor will restart the old client, and we start accumulating unused processes.
  * if I link myself to the connection, when it dies my process will die as well and both will be restarted by respective supervisors - the problem is my process will have no idea about the restarted client and will start a new one. Once again we're left with zombie processes.

Is there something I'm missing?

**Comment by bitwalker** [comment]
You don't have to use the exirc supervisor - all you need to do is start the client under your own supervisor tree in whatever way works best for your application. Realistically, exirc probably doesn't need a supervisor tree of it's own, but I think my preference would be to extend the API to allow naming the clients so that even if a given client restarts, the API allows you to talk to whatever pid is registered for that name. Right now the ExIrc module API doesn't expose a function which would let you name the child which is started, but it would be pretty trivial to add.

**Comment by michalmuskala** [comment]
After some thinking and some discussion on IRC around this, I settled on starting the client process under my supervisor (`rest_for_all`) as a temporary worker monitored and managed by a proper GenServer that is under the same supervisor as a `permanent` worker..

It would make perfect sense though to have clients supervised by exirc, if the restart strategy was `temporary` instead of `transient`. Once the client is restarted the owner looses track of it, and can't do anything anyway. With this you could monitor the client process or link yourself to it so proper error handling is maintained. This is what [gun](https://github.com/ninenines/gun/blob/master/src/gun_sup.erl) does with it's supervised connections. It's explained in the [gun docs](https://github.com/ninenines/gun/blob/master/doc/src/guide/connect.asciidoc#monitoring-the-connection-process) how to properly monitor the process and react to failures.

I also think that the client process should monitor the process that started it (let's call it the owner) and exit in case the client crashes. Otherwise again we might be left with zombie processes.

If you agree with those changes I can work on them.
